Update __init__.py
Fixed this error, caused by performing string manipulation on a function:
```
related_admin/__init__.py", line 69, in __new__
    if '__' in field[1:-1] and not hasattr(new_class, field):
TypeError: 'function' object is not subscriptable
```
`list_display` can also contain `functions`. Added check that fields in `list_display` are only strings.